version: '3.8'
services:
  app:
    build: .
    volumes:
      - ./downloads:/downloads
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
  worker:
    build: .
    command: [ "python", "-m", "app.worker" ]
    volumes:
      - ./downloads:/downloads
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      replicas: 3  # кол-во одновременных воркеров (чтобы не забивать канал скачивания видео)
      resources:
        limits:
          cpus: "0.5"
          memory: "512M"
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status" ]
      interval: 5s
      timeout: 10s
      retries: 10
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10